-- Emits one JSON object per critical table; metadata only, no application rows.
SELECT JSON_OBJECT(
  'table', t.TABLE_NAME,
  'columns', (SELECT JSON_ARRAYAGG(JSON_OBJECT(
    'COLUMN_NAME', c.COLUMN_NAME, 'COLUMN_TYPE', c.COLUMN_TYPE,
    'IS_NULLABLE', c.IS_NULLABLE, 'COLUMN_DEFAULT', c.COLUMN_DEFAULT,
    'EXTRA', c.EXTRA) ORDER BY c.ORDINAL_POSITION)
    FROM information_schema.COLUMNS c
    WHERE c.TABLE_SCHEMA=t.TABLE_SCHEMA AND c.TABLE_NAME=t.TABLE_NAME),
  'indexes', (SELECT JSON_ARRAYAGG(JSON_OBJECT(
    'INDEX_NAME', s.INDEX_NAME, 'NON_UNIQUE', s.NON_UNIQUE,
    'SEQ_IN_INDEX', s.SEQ_IN_INDEX, 'COLUMN_NAME', s.COLUMN_NAME,
    'SUB_PART', s.SUB_PART) ORDER BY s.INDEX_NAME,s.SEQ_IN_INDEX)
    FROM information_schema.STATISTICS s
    WHERE s.TABLE_SCHEMA=t.TABLE_SCHEMA AND s.TABLE_NAME=t.TABLE_NAME),
  'foreign_keys', (SELECT COALESCE(JSON_ARRAYAGG(JSON_OBJECT(
    'CONSTRAINT_NAME', k.CONSTRAINT_NAME, 'ORDINAL_POSITION', k.ORDINAL_POSITION,
    'COLUMN_NAME', k.COLUMN_NAME, 'REFERENCED_TABLE_NAME', k.REFERENCED_TABLE_NAME,
    'REFERENCED_COLUMN_NAME', k.REFERENCED_COLUMN_NAME,
    'UPDATE_RULE', r.UPDATE_RULE, 'DELETE_RULE', r.DELETE_RULE)
    ORDER BY k.CONSTRAINT_NAME,k.ORDINAL_POSITION), JSON_ARRAY())
    FROM information_schema.KEY_COLUMN_USAGE k
    JOIN information_schema.REFERENTIAL_CONSTRAINTS r
      ON r.CONSTRAINT_SCHEMA=k.CONSTRAINT_SCHEMA AND r.CONSTRAINT_NAME=k.CONSTRAINT_NAME
    WHERE k.TABLE_SCHEMA=t.TABLE_SCHEMA AND k.TABLE_NAME=t.TABLE_NAME
      AND k.REFERENCED_TABLE_NAME IS NOT NULL),
  'check_constraints', (SELECT COALESCE(JSON_ARRAYAGG(JSON_OBJECT(
    'CONSTRAINT_NAME', cc.CONSTRAINT_NAME, 'CHECK_CLAUSE', cc.CHECK_CLAUSE)
    ORDER BY cc.CONSTRAINT_NAME), JSON_ARRAY())
    FROM information_schema.TABLE_CONSTRAINTS tc
    JOIN information_schema.CHECK_CONSTRAINTS cc
      ON cc.CONSTRAINT_SCHEMA=tc.CONSTRAINT_SCHEMA AND cc.CONSTRAINT_NAME=tc.CONSTRAINT_NAME
    WHERE tc.TABLE_SCHEMA=t.TABLE_SCHEMA AND tc.TABLE_NAME=t.TABLE_NAME
      AND tc.CONSTRAINT_TYPE='CHECK')
)
FROM information_schema.TABLES t
WHERE t.TABLE_SCHEMA=DATABASE() AND t.TABLE_TYPE='BASE TABLE'
  AND t.TABLE_NAME IN ('players','player_stats','posts','standings','teams','fixtures','fixture_events','fixture_scores','predictions')
ORDER BY t.TABLE_NAME;
